# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/rrwth/OneDrive/Documents/College/ECE350/Checkpoints/processor/Vivado/Vivado.runs/impl_1/.Xil/Vivado-65832-DESKTOP-VN8895K/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
